# Generated by Django 5.0.1 on 2024-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='pub_data',
            field=models.DateTimeField(verbose_name='data depublicacao'),
        ),
    ]
