# Generated by Django 5.0.3 on 2024-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_alter_aluno_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='fotoPerfil',
            field=models.TextField(default='userdefault.png'),
        ),
    ]
