# Generated by Django 5.0.3 on 2024-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='votosFeitos',
            field=models.IntegerField(default=0),
        ),
    ]
